Repository harvester/dashboard, pull requests merged in 2024-09, with the labels that each got.

#1114 Filter out witness node from VM migration dropdown
  pkg/harvester/dialog/HarvesterMigrationDialog.vue
Labels: Bug Fix

#1120 Fix harvester support link does not link to support page when embedded Rancher 2.9
  pkg/harvester/pages/c/_cluster/support/index.vue
Labels: Bug Fix, Require backport v1.3

#1129 Fix backup-target setting doesn't set to the latest value
  pkg/harvester/components/SettingList.vue
Labels: Bug Fix

#1110 [ui-strings] Consistent language use applied across UI strings
  pkg/harvester/config/harvester-map.js
  pkg/harvester/config/harvester.js
  pkg/harvester/l10n/en-us.yaml
  shell/assets/translations/en-us.yaml
Labels: Documentation

#1135 Check harvester resource quota schema to prevent unknown schema error
  pkg/harvester/config/harvester.js
  pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue
  pkg/harvester/list/kubevirt.io.virtualmachine.vue
  pkg/harvester/store/harvester-store/actions.ts
  shell/components/ExplorerProjectsNamespaces.vue
  shell/list/namespace.vue
Labels: Bug Fix

#1137 Add cancelAction in VM create page
  pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
  pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Labels: Enhancement

#1109 Support CPU Pinning
  pkg/harvester/config/labels-annotations.js
  pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
  pkg/harvester/dialog/HarvesterMigrationDialog.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
  pkg/harvester/formatters/HarvesterCPUPinning.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/list/harvesterhci.io.host.vue
  pkg/harvester/list/kubevirt.io.virtualmachine.vue
  pkg/harvester/models/harvester/node.js
  pkg/harvester/models/kubevirt.io.virtualmachine.js
  shell/assets/translations/en-us.yaml
Labels: New Feature

#1113 Take image virtual size into account when creating Volumes
  pkg/harvester/edit/harvesterhci.io.volume.vue
Labels: Enhancement

#1124 Add mergify.yml to automatically open backport PR
  .github/mergify.yml
Labels: Enhancement

#1132 Replace $copyText with copyTextToClipboard function
  package.json
  shell/components/CopyCode.vue
  shell/components/CopyToClipboard.vue
  shell/components/CopyToClipboardText.vue
  shell/components/StatusTable.vue
  shell/components/__tests__/CopyCode.test.ts
  shell/components/form/Password.vue
  shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.tests.ts
  shell/initialize/index.js
  shell/models/management.cattle.io.cluster.js
  shell/package.json
  shell/plugins/vue-clipboard2.js
  shell/utils/clipboard.js
  yarn.lock
Labels: Bug Fix, Require backport v1.3

#1105 Reserved storage size in the dashboard isn't useful
  pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
  pkg/harvester/formatters/HarvesterStorageUsed.vue
  pkg/harvester/list/harvesterhci.io.dashboard.vue
  pkg/harvester/list/harvesterhci.io.host.vue
  shell/assets/translations/en-us.yaml
  shell/components/HardwareResourceGauge.vue
Labels: Bug Fix, Require backport v1.3, Backport to v1.4

#1128 Add additional-guest-memory-overhead-ratio setting
  pkg/harvester/components/settings/additional-guest-memory-overhead-ratio.vue
  pkg/harvester/config/settings.js
  pkg/harvester/l10n/en-us.yaml
Labels: New Feature

#1156 Fix: missing allocated translation key
  pkg/harvester/formatters/HarvesterStorageUsed.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/list/harvesterhci.io.dashboard.vue
Labels: Bug Fix, Require backport v1.3

#1160 Pin verdaccio@5.32.2 for check-plugin CI job
  shell/scripts/test-plugins-build.sh
Labels: CI/CD

#1162 Detect Red Hat linux OS Type like Ubuntu and OpenSUSE
  pkg/harvester/mixins/harvester-vm/index.js
Labels: Enhancement

#1165 Add encrypt image and decrypt image actions
  pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue
  pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Labels: Enhancement

#1168 Fix Node list in VMs Migrate dialog
  pkg/harvester/dialog/HarvesterMigrationDialog.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/models/kubevirt.io.virtualmachine.js
Labels: Bug Fix

#1154 Add provisioned vGpus in VM's devices list.
  pkg/harvester/config/labels-annotations.js
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/index.vue
  pkg/harvester/models/kubevirt.io.virtualmachine.js
Labels: Enhancement

#1103 Add VM schedules pages
  package.json
  pkg/harvester/components/FilterVMSchedule.vue
  pkg/harvester/config/harvester.js
  pkg/harvester/config/labels-annotations.js
  pkg/harvester/config/table-headers.js
  pkg/harvester/detail/harvesterhci.io.schedulevmbackup/BackupList.vue
  pkg/harvester/detail/harvesterhci.io.schedulevmbackup/SnapshotList.vue
  pkg/harvester/detail/harvesterhci.io.schedulevmbackup/index.vue
  pkg/harvester/detail/harvesterhci.io.virtualmachinebackup/index.vue
  pkg/harvester/edit/harvesterhci.io.schedulevmbackup.vue
  pkg/harvester/edit/harvesterhci.io.virtualmachinebackup.vue
  pkg/harvester/edit/harvesterhci.io.vmsnapshot.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/container.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
  pkg/harvester/formatters/BackupCreatedFrom.vue
  pkg/harvester/formatters/HarvesterCronExpression.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/list/harvesterhci.io.schedulevmbackup.vue
  pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
  pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
  pkg/harvester/mixins/harvester-vm/index.js
  pkg/harvester/models/harvesterhci.io.schedulevmbackup.js
  pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js
  pkg/harvester/models/kubevirt.io.virtualmachine.js
  pkg/harvester/types.ts
  pkg/harvester/utils/cron.js
  pkg/rancher-components/package.json
  pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
  shell/package.json
  yarn.lock
Labels: New Feature, Backport to v1.4
