Repository harvester/dashboard, pull requests merged in 2024-10, with the labels that each got.

#1176 [BUG] Final edits to the UI strings
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/list/harvesterhci.io.logging.clusterflow.vue
  pkg/harvester/list/harvesterhci.io.logging.clusteroutput.vue
  pkg/harvester/list/harvesterhci.io.logging.flow.vue
  pkg/harvester/list/harvesterhci.io.logging.output.vue
Labels: Documentation

#1076 Host local storage support
  pkg/harvester/components/settings/csi-driver-config.vue
  pkg/harvester/config/harvester-map.js
  pkg/harvester/config/labels-annotations.js
  pkg/harvester/detail/harvesterhci.io.host/HarvesterHostDisk.vue
  pkg/harvester/detail/harvesterhci.io.host/index.vue
  pkg/harvester/edit/harvesterhci.io.host/HarvesterDisk.vue
  pkg/harvester/edit/harvesterhci.io.host/index.vue
  pkg/harvester/edit/harvesterhci.io.storage/index.vue
  pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue
  pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v2.vue
  pkg/harvester/edit/harvesterhci.io.storage/provisioners/lvm.driver.harvesterhci.io.vue
  pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue
  pkg/harvester/edit/harvesterhci.io.volume.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/mixins/harvester-vm/index.js
  pkg/harvester/models/harvester/node.js
  pkg/harvester/models/harvester/storage.k8s.io.storageclass.js
  pkg/harvester/models/harvesterhci.io.blockdevice.js
  pkg/harvester/types.ts
  shell/assets/translations/en-us.yaml
  shell/models/persistentvolume.js
Labels: New Feature

#1200 Root disk volume accessMode should be RWX
  pkg/harvester/mixins/harvester-vm/index.js
Labels: Backport to v1.4

#1202 feat: add clone capability back for LVM volume
  pkg/harvester/models/harvester/persistentvolumeclaim.js
  pkg/harvester/models/kubevirt.io.virtualmachine.js
Labels: Backport to v1.4

#1209 feat: Change LH V2 enablement from Preview to Experimental
  pkg/harvester/components/SettingList.vue
  pkg/harvester/config/settings.js
  pkg/harvester/l10n/en-us.yaml
Labels: Backport to v1.4

#1211 Change upgrade error banner to red color
  pkg/harvester/components/HarvesterUpgrade.vue
Labels: Backport to v1.4
