Repository harvester/dashboard, pull requests merged in 2024-08, with the labels that each got.

#1093 fix: vlan id input mask
  pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
Labels: bug

#1112 Add image restoring status
  pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Labels: Enhancement

#973 Show error message upon each retry failure
  pkg/harvester/models/harvesterhci.io.upgrade.js
  pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Labels: Enhancement

#1115 Fixed links to documents from old Harvester versions (backport #1107)
  pkg/harvester/l10n/en-us.yaml
Labels: Backport PR

#1108 feat: Add ability to enable Longhorn V2 Data Engine
  pkg/harvester/components/SettingList.vue
  pkg/harvester/config/settings.js
  pkg/harvester/l10n/en-us.yaml
Labels: New Feature

#1117 Move reserved memory out from Read More in VM and VM template detail pages
  pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
  pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
Labels: Enhancement
