Repository harvester/dashboard, pull requests merged in 2025-02, with the labels that each got.

#1270 feat: cluster output select dropdown should show meaningful sentence if no options available
  shell/components/form/LabeledSelect.vue
Labels: Require backport v1.4

#1273 update actions/upload-artifact to v4
  .github/workflows/test.yaml
  shell/creators/pkg/files/.github/workflows/build-extension.yml
Labels: Require backport v1.3, Require backport v1.4

#1045 Add `Labels` tab to `Virtual Machines` resource page
  pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
  pkg/harvester/l10n/en-us.yaml
  shell/components/form/KeyValue.vue
  shell/components/form/Labels.vue
Labels: Enhancement

#1276 The hints on the branding page is using the wrong product name
  pkg/harvester/l10n/en-us.yaml
  pkg/harvester/pages/c/_cluster/brand/index.vue
Labels: Require backport v1.3, Require backport v1.4

#1280 Add refreshIntervalInSeconds in backup target edit page
  pkg/harvester/components/settings/backup-target.vue
  pkg/harvester/l10n/en-us.yaml
Labels: Require backport v1.4
